//
//  HomeScreenViewModel.swift
//  NarutoWiki
//
//  Created by Brenner on 27/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class HomeScreenViewModel: NSObject {
    
}

// MARK: - Extensions
extension HomeScreenViewModel: HomeScreenViewModelProtocol { }

// MARK: - TableView
extension HomeScreenViewModel: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: CharacterTableViewCell.reuseIdentifier) as? CharacterTableViewCell else { fatalError("Could not dequeue cell with identifier: \(CharacterTableViewCell.reuseIdentifier)") }
        return cell
    }
}
