//
//  HomeScreenViewModelProtocol.swift
//  NarutoWiki
//
//  Created by Brenner on 27/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import Foundation
import UIKit

protocol HomeScreenViewModelProtocol: UITableViewDelegate, UITableViewDataSource { }


