//
//  HomeScreenViewModel.swift
//  NarutoWiki
//
//  Created by Brenner on 27/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class HomeScreenViewModel: NSObject {
    
    private let homeScreenServices: HomeScreenServicesProtocol
    
    var characters: [Character]? {
        didSet {
            reloadTableView?()
        }
    }
    var reloadTableView: (() -> Void)?
    
    init(homeScreenServices: HomeScreenServicesProtocol) {
        self.homeScreenServices = homeScreenServices
    }
    
    func viewDidLoad() {
        fetchCharacters()
    }
    
    private func fetchCharacters() {
        homeScreenServices.fetchAllCharacters { result in
            switch result {
            case .success(let characterList):
                self.characters = characterList
            case .failure: break
            }
        }
    }
}

// MARK: - Extensions
extension HomeScreenViewModel: HomeScreenViewModelProtocol { }
