//
//  HomeScreenViewModel.swift
//  NarutoWiki
//
//  Created by Brenner on 27/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class HomeScreenViewModel: NSObject {
    var characters: [Character]?
}

// MARK: - Extensions
extension HomeScreenViewModel: HomeScreenViewModelProtocol {
   
}
